import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup,request} from './enrichment-store.test.js';
import {syncTargets,saveSource} from '../src/paper-enrichment.js';
import {sha256} from '../src/review-v2.js';
import {importDocument,importBibliography,documentResponse,publicAssets,retainProviderBibliography,privateBinaryStore,servePublicAssets} from '../src/enrichment-assets.js';
import migration from '../src/enrichment-delivery-migration.json' with {type:'json'};
const pdf=Uint8Array.from(Buffer.from('%PDF-1.7\nSynthetic PDF transport fixture only, not a production paper.\n%%EOF'));
const hash=bytes=>crypto.subtle.digest('SHA-256',bytes).then(v=>Buffer.from(v).toString('hex'));
async function fixture(){const x=setup();await x.core.ready;await x.core.machine(await request({operation:'activate'}));const env=await x.core.environment();const candidate={id:'CAND-ASSET-FIXTURE',title:'Synthetic asset fixture',doi:'',sourceLinks:['https://docs.iza.org/fixture.pdf']};await syncTargets(env,{schemaVersion:1,records:[candidate]},Date.now());const target=x.db.prepare('SELECT * FROM enrichment_targets').get();const text='Privately retained original full text fixture.';const sourceId=await saveSource(env,target,{provider:'Fixture',source_url:candidate.sourceLinks[0],evidence_kind:'full_text',text},Date.now());const document={input_sha256:target.input_sha256,source_id:sourceId,pdf_sha256:await hash(pdf),source_text_sha256:await sha256(text),bytes_base64:Buffer.from(pdf).toString('base64'),retention_basis:'Synthetic private research test',licence_status:'Not verified for redistribution',licence_url:null,attribution:'Synthetic software fixture',visibility:'private',rights_verified:false};return{...x,env,candidate,target,text,document}}
test('delivery migration is additive, hash-bound and both tables are immutable',async()=>{assert.equal(migration.sql,readFileSync(new URL('../migrations/0006_enrichment_delivery_assets.sql',import.meta.url),'utf8'));assert.equal(await sha256(migration.sql),migration.sha256);const x=await fixture();const d=await importDocument(x.env,x.target.target_id,x.document);assert.throws(()=>x.db.prepare('UPDATE enrichment_documents SET visibility=? WHERE document_id=?').run('public',d.document_id),/immutable/);assert.throws(()=>x.db.prepare('DELETE FROM enrichment_documents').run(),/immutable/)});
test('original bytes are read back through the reader with range and HEAD support',async()=>{const x=await fixture(),d=await importDocument(x.env,x.target.target_id,x.document);const full=await documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document'));assert.equal(full.headers.get('Content-Type'),'application/pdf');assert.deepEqual(new Uint8Array(await full.arrayBuffer()),pdf);const r=await documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document',{headers:{Range:'bytes=0-4'}}));assert.equal(r.status,206);assert.equal(await r.text(),'%PDF-');const head=await documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document',{method:'HEAD'}));assert.equal(await head.text(),'');assert.equal(Number(head.headers.get('Content-Length')),pdf.length);const bad=await documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document',{headers:{Range:'bytes=999999-'}}));assert.equal(bad.status,416)});
test('private originals never become public; explicit rights remain necessary',async()=>{const x=await fixture(),d=await importDocument(x.env,x.target.target_id,x.document);assert.equal((await publicAssets(x.env,x.candidate.id)).documents.length,0);await assert.rejects(documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document'),{publicOnly:true}),/not_public/);await assert.rejects(importDocument(x.env,x.target.target_id,{...x.document,visibility:'public'}),/authorisation/)});
test('an independently supplied reusable licence allows only the current immutable rights record',async()=>{const x=await fixture();const data={...x.document,visibility:'public',rights_verified:true,licence_url:'https://creativecommons.org/licenses/by/4.0/',licence_status:'Synthetic verified licence'};const d=await importDocument(x.env,x.target.target_id,data,Date.now());assert.equal((await publicAssets(x.env,x.candidate.id)).documents.length,1);await importDocument(x.env,x.target.target_id,{...x.document,retention_basis:'Synthetic subsequent private-only rights correction'},Date.now()+1000);await assert.rejects(documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document'),{publicOnly:true}),/not_public/);assert.equal((await publicAssets(x.env,x.candidate.id)).documents.length,0)});
test('wrong hashes, source text, stale input, HTML and tampered bytes fail closed',async()=>{const x=await fixture();for(const data of [{...x.document,pdf_sha256:'0'.repeat(64)},{...x.document,source_text_sha256:'0'.repeat(64)},{...x.document,input_sha256:'0'.repeat(64)},{...x.document,bytes_base64:Buffer.from('<html>not a PDF</html>').toString('base64')}])await assert.rejects(importDocument(x.env,x.target.target_id,data));const d=await importDocument(x.env,x.target.target_id,x.document);x.kv.set('document:'+x.document.pdf_sha256+':0',new Uint8Array(pdf.length));await assert.rejects(documentResponse(x.env,x.target.target_id,d.document_id,new Request('https://x/document')),/integrity/)});
test('binary chunks preserve large bytes, idempotency and missing-chunk failures',async()=>{const x=setup(),store=privateBinaryStore(x.storage),bytes=new Uint8Array(200000).fill(57),h=await hash(bytes);await store.put(h,bytes);assert.deepEqual(await store.get(h),bytes);await store.put(h,bytes);x.kv.delete('document:'+h+':2');await assert.rejects(store.get(h),/integrity/);await assert.rejects(store.put(h,new Uint8Array(4194305)),/invalid/)});
function bibliography(x,n=101){return{input_sha256:x.target.input_sha256,source_id:x.document.source_id,scope:'paper_bibliography',coverage:'source_complete',declared_count:n,entries:Array.from({length:n},(_,i)=>({position:i+1,title:'Synthetic reference '+i,authors:[],year:null,venue:null,doi:null,url:null,source_locator:'References item '+(i+1),unresolved_identity:true}))}}
test('bibliography preserves unresolved identities and paginates a frozen finite snapshot',async()=>{const x=await fixture(),data=bibliography(x);await importBibliography(x.env,x.target.target_id,data);const first=await publicAssets(x.env,x.candidate.id);assert.equal(first.bibliography.entries.length,100);assert.equal(first.bibliography.next_offset,100);const second=await publicAssets(x.env,x.candidate.id,100,first.bibliography.revision);assert.equal(second.bibliography.entries.length,1);assert.equal(second.bibliography.next_offset,null);assert.ok(second.bibliography.entries[0].unresolved_identity);const serial=JSON.stringify(first);assert.ok(!serial.includes(x.document.source_id));assert.ok(!serial.includes('source_locator'));await assert.rejects(publicAssets(x.env,x.candidate.id,100,'a'.repeat(64)),/snapshot_changed/)});
test('bibliography rejects invented completeness, duplicate positions, secrets and invalid missingness',async()=>{const x=await fixture();const data=bibliography(x,2);for(const d of [{...data,declared_count:null},{...data,coverage:'not_reported'},{...data,entries:[data.entries[0],data.entries[0]]},{...data,entries:[{...data.entries[0],title:'Bearer secretsecretsecret'}]}])await assert.rejects(importBibliography(x.env,x.target.target_id,d));assert.equal(x.db.prepare('SELECT COUNT(*) n FROM enrichment_bibliography_snapshots').get().n,0)});
test('machine bridge requires signatures and reads the same retained PDF route',async()=>{const x=await fixture();const r=await x.core.machine(await request({operation:'document',target_id:x.target.target_id,document:x.document}));assert.equal(r.status,201);const d=await r.json();const checked=await x.core.machine(await request({operation:'document-check',target_id:x.target.target_id,document_id:d.document_id}));assert.equal((await checked.json()).readable,true);const no=await servePublicAssets(new Request('https://x/api/public-paper-assets?id='+x.candidate.id+'&document='+d.document_id),x.core);assert.equal(no.status,404)});

test('provider bibliography never substitutes for the full-paper references',async()=>{
 const x=await fixture();const record=JSON.parse(x.target.record_json);record.doi='10.1234/test';const {canonicalJson}=await import('../src/review-v2.js');const input=await sha256(canonicalJson(record));x.db.prepare('UPDATE enrichment_targets SET record_json=?,input_sha256=? WHERE target_id=?').run(canonicalJson(record),input,x.target.target_id);const target={...x.target,input_sha256:input,record_json:canonicalJson(record)};
 await saveSource(x.env,target,{provider:'Crossref',source_url:'https://api.crossref.org/works/10.1234/test',evidence_kind:'metadata',text:canonicalJson({DOI:record.doi,'reference-count':2,reference:[{'article-title':'Synthetic cited work',DOI:'10.1234/cited',author:'Synthetic author',year:'2020'},{unstructured:'Unresolved synthetic citation'}]})},Date.now());
 const result=await retainProviderBibliography(x.env,target.target_id);assert.equal(result.entries_count,2);const out=await publicAssets(x.env,x.candidate.id);assert.equal(out.bibliography.scope,'provider_references');assert.equal(out.bibliography.entries[0].title,'Synthetic cited work');assert.equal(out.bibliography.entries[1].unresolved_identity,true);assert.equal(out.bibliography.entries[1].title,null);
 assert.equal((await retainProviderBibliography(x.env,target.target_id)).replayed,true);
});

test('public assets expose only closed identity fields from full production-shaped records',async()=>{
 const x=await fixture();const {canonicalJson}=await import('../src/review-v2.js');const record={...x.candidate,authors:['Synthetic author'],year:2020,reviewStatus:'pending'};x.db.prepare('UPDATE enrichment_targets SET record_json=?,input_sha256=? WHERE target_id=?').run(canonicalJson(record),await sha256(canonicalJson(record)),x.target.target_id);
 const out=await publicAssets(x.env,x.candidate.id);assert.deepEqual(Object.keys(out.candidate).sort(),['doi','id','sourceLinks','title']);assert.equal(out.availability,'registered');
});
