import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { runEnrichment,syncTargets,saveSource,storeExtraction,validateExtraction,validateRegistry,handlePaperEnrichment } from '../src/paper-enrichment.js';
import { sha256 } from '../src/review-v2.js';
const now=Date.parse('2026-09-11T10:00:00Z');
function setup(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
 sqlite.exec(readFileSync(new URL('../migrations/0003_paper_enrichment.sql',import.meta.url),'utf8'));
 const db={sqlite,prepare(sql){let v=[];return{bind(...a){v=a;return this},async first(){return sqlite.prepare(sql).get(...v)||null},async all(){return{results:sqlite.prepare(sql).all(...v)}},async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...v).changes)}}}}},async batch(ss){sqlite.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 const store=new Map(),env={CURATOR_LOGIN:'owner',PAPER_ENRICHMENT_ENABLED:'true',REVIEW_DB:db,REVIEW_EVIDENCE:{async put(k,v){store.set(k,v)},async get(k){return store.has(k)?{async text(){return store.get(k)}}:null}}};
 return{env,db,store};
}
const record={id:'CAND-SYNTHETIC-001',title:'Synthetic test paper',doi:'10.1234/synthetic',sourceLinks:['https://example.org/paper']};
const registry=(r=record)=>({schemaVersion:1,records:[r]});
const success=async()=>Response.json({message:{DOI:record.doi,title:[record.title],abstract:'Synthetic authored evidence. Second sentence.'}});
const targetOf=(db)=>db.sqlite.prepare('SELECT * FROM enrichment_targets LIMIT 1').get();
const facts=(status='not_verifiable')=>({status,value:null,evidence_span_ids:[],origin:'source'});
const reported=(value='Synthetic result',origin='source')=>({status:'reported',value,evidence_span_ids:['S1'],origin});
function envelope(target,source){return{schema_version:1,protocol_version:'CILE-ENRICH-1',codebook_version:'1.0.0',target_id:target.target_id,input_sha256:target.input_sha256,generated_by:{agent:'Synthetic fixture',model:null,prompt_sha256:null},source_ids:[source.source_id],source_coverage:'abstract_only',spans:[{id:'S1',source_id:source.source_id,start_offset:0,end_offset:9,locator:'Abstract, first sentence'}],summary:reported(),contribution:facts(),research_question:facts(),infiltration_definition:facts(),infiltration_operationalisation:facts(),authors_limitations:facts(),analyst_limitations:facts(),studies:[],datasets:[],analyses:[],variable_uses:[],findings:[],framework:{status:'proposed',primary:'diagnosis',rationale:reported('Synthetic coding rationale','analyst'),secondary:[],alternative:null}}}
async function sourceSetup(){const x=setup();await syncTargets(x.env,registry(),now);const target=targetOf(x.db);const id=await saveSource(x.env,target,{provider:'Fixture',source_url:'https://example.org/abstract',evidence_kind:'abstract',text:'Synthetic test evidence.'},now);const source={...x.db.sqlite.prepare('SELECT * FROM enrichment_sources').get(),text:'Synthetic test evidence.'};return{...x,target,source,input:envelope(target,source),id}}

test('empty migration and repeatable registry synchronisation',async()=>{const{env,db}=setup();assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_targets').get().n,0);await syncTargets(env,registry(),now);await syncTargets(env,registry(),now+1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_jobs').get().n,4);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_inputs').get().n,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM enrichment_jobs WHERE status='blocked'").get().n,2)});
test('registry rejects duplicate or malformed candidates before writing',()=>{assert.throws(()=>validateRegistry({schemaVersion:1,records:[record,record]}),/invalid_registry_record/);assert.throws(()=>validateRegistry(registry({...record,sourceLinks:['http://example.org']})),/invalid_registry_record/)});
test('input changes supersede old jobs without erasing snapshots',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);await syncTargets(env,registry({...record,title:'Changed synthetic title'}),now+1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_inputs').get().n,2);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM enrichment_jobs WHERE status='superseded'").get().n,4)});
test('disabled runner and unavailable private storage do not perform network calls',async()=>{const{env}=setup();let calls=0;const fetcher=async()=>{calls++;throw Error('no')};assert.equal((await runEnrichment({...env,PAPER_ENRICHMENT_ENABLED:'false'},{now,fetcher})).status,'disabled');assert.equal((await runEnrichment({...env,REVIEW_EVIDENCE:null},{now,fetcher})).status,'blocked');assert.equal(calls,0)});
test('metadata saves privately with readback; repeated hourly slot makes no new requests',async()=>{const{env,db,store}=setup();let calls=0;const fetcher=async()=>{calls++;return success()};const r=await runEnrichment(env,{now,registry:registry(),fetcher});assert.equal(r.status,'completed',JSON.stringify(r));assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_sources').get().n,2);assert.equal(store.size,2);assert.equal((await runEnrichment(env,{now:now+60000,registry:registry(),fetcher})).status,'slot_already_observed');assert.equal(calls,1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_proposals').get().n,0)});
test('exact DOI with conflicting title cannot become evidence',async()=>{const{env,db}=setup();const r=await runEnrichment(env,{now,registry:registry(),fetcher:async()=>Response.json({message:{DOI:record.doi,title:['Another article'],abstract:'Wrong source'}})});assert.equal(r.status,'failed');assert.equal(r.error_code,'identity_conflict');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_sources').get().n,0)});
test('DOI-less target persists and reports identifier resolution block',async()=>{const{env,db}=setup();const r=await runEnrichment(env,{now,registry:registry({...record,doi:''}),fetcher:async()=>{throw Error('must not fetch')}});assert.equal(r.error_code,'identifier_resolution_required');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_targets').get().n,1)});
test('missing abstract is not a claim that no abstract exists',async()=>{const{env,db}=setup();await runEnrichment(env,{now,registry:registry(),fetcher:async()=>Response.json({message:{DOI:record.doi,title:[record.title]}})});const j=db.sqlite.prepare("SELECT checkpoint_json FROM enrichment_jobs WHERE kind='metadata'").get();assert.equal(JSON.parse(j.checkpoint_json).abstract_status,'not_returned')});
test('provider refusal does not enable another or paid provider',async()=>{const{env,db}=setup();await runEnrichment(env,{now,registry:registry(),fetcher:async()=>new Response('',{status:401})});assert.equal(db.sqlite.prepare("SELECT error_code FROM enrichment_jobs WHERE kind='metadata'").get().error_code,'provider_authentication_required')});
test('rate limits retain Retry-After and are not successful empty results',async()=>{const{env,db}=setup();const r=await runEnrichment(env,{now,registry:registry(),fetcher:async()=>new Response('',{status:429,headers:{'Retry-After':'20000'}})});assert.equal(r.status,'failed');const j=db.sqlite.prepare("SELECT * FROM enrichment_jobs WHERE kind='metadata'").get();assert.equal(j.status,'pending');assert.ok(Date.parse(j.due_at)>=now+20000000)});
test('source readback failure prevents evidence registration',async()=>{const{env,db}=setup();env.REVIEW_EVIDENCE.get=async()=>null;const r=await runEnrichment(env,{now,registry:registry(),fetcher:success});assert.equal(r.error_code,'source_readback_failed');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_sources').get().n,0)});
test('registry failure does not suppress a previously persisted executable job',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);const r=await runEnrichment(env,{now,fetcher:async(url)=>url.includes('colazeta.github.io')?new Response('',{status:503}):success()});assert.equal(r.status,'partial');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_sources').get().n,2)});
test('citation pages have resumable checkpoints and distinct directions',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);db.sqlite.exec("UPDATE enrichment_jobs SET status='blocked' WHERE kind='metadata'");const fetcher=async(url)=>url.includes('filter=')?Response.json({results:[{id:'https://openalex.org/W3',doi:null,title:'Citing fixture'}],meta:{count:2,next_cursor:url.includes('cursor=*')?'next-page':null}}):Response.json({id:'https://openalex.org/W1',doi:'https://doi.org/'+record.doi,title:record.title,referenced_works:['https://openalex.org/W2'],cited_by_count:2});for(let i=0;i<3;i++){const r=await runEnrichment(env,{now:now+i*3600000,registry:registry(),fetcher});assert.notEqual(r.status,'failed',JSON.stringify(r))}assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_citation_observations').get().n,2);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM enrichment_citation_coverage WHERE direction='incoming'").get().n,2);assert.equal(db.sqlite.prepare("SELECT status FROM enrichment_jobs WHERE kind='citations'").get().status,'completed')});
test('missing pagination metadata is not provider-complete',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);db.sqlite.exec("UPDATE enrichment_jobs SET status='blocked' WHERE kind='metadata'");const fetcher=async(url)=>url.includes('filter=')?Response.json({results:[],meta:{}}):Response.json({id:'https://openalex.org/W1',doi:record.doi,title:record.title,referenced_works:[],cited_by_count:1});await runEnrichment(env,{now,registry:registry(),fetcher});const r=await runEnrichment(env,{now:now+3600000,registry:registry(),fetcher});assert.equal(r.error_code,'invalid_citation_page')});
test('untrusted extra fields, forged source coverage and cross-paper spans are rejected',async()=>{const{target,source,input}=await sourceSetup();assert.throws(()=>validateExtraction({...input,eligibility:'eligible_core'},target,[source]),/schema_extra/);assert.throws(()=>validateExtraction({...input,source_coverage:'full_text'},target,[source]),/unsupported_source_coverage/);assert.throws(()=>validateExtraction(input,target,[{...source,target_id:'OTHER'}]),/invalid_source_scope/)});
test('reported facts require valid locatable evidence',async()=>{const{target,source,input}=await sourceSetup();input.summary.evidence_span_ids=[];assert.throws(()=>validateExtraction(input,target,[source]),/reported_fact_requires_evidence/);input.summary=reported();input.spans[0].end_offset=999;assert.throws(()=>validateExtraction(input,target,[source]),/invalid_source_span/)});
test('missingness, abstention and framework roles are not silently conflated',async()=>{const{target,source,input}=await sourceSetup();input.summary={...facts(),value:'invented'};assert.throws(()=>validateExtraction(input,target,[source]),/missingness_requires_null/);input.summary=reported();input.framework.status='insufficient_evidence';assert.throws(()=>validateExtraction(input,target,[source]),/abstention_cannot_assign_categories/)});
test('a grounded proposal is immutable, private, idempotent and never an eligibility decision',async()=>{const{env,db,target,input}=await sourceSetup();const a=await storeExtraction(env,target,input,now),b=await storeExtraction(env,target,input,now+1);assert.equal(a.proposal_id,b.proposal_id);assert.equal(b.replayed,true);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_proposals').get().n,1);assert.throws(()=>db.sqlite.exec('DELETE FROM enrichment_proposals'),/append_only/);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='screening_decisions_v2'").get().n,0)});
test('altered private bytes cannot support a proposal',async()=>{const{env,target,input,store}=await sourceSetup();for(const key of store.keys())store.set(key,'Changed');await assert.rejects(storeExtraction(env,target,input,now),/source_integrity_failure/)});
test('owner-only endpoints do not return research contents without a session',async()=>{const{env}=setup();const r=await handlePaperEnrichment(new Request('https://example.org/api/paper-enrichment/status'),env,{login:'other'});assert.equal(r.status,401)});
test('active leases prevent overlapping attempts and expired leases recover',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);db.sqlite.prepare("INSERT INTO enrichment_runs VALUES ('OLD','oa-2026-09-08','2026-09-11T09',?,NULL,?,'running',NULL,NULL)").run(new Date(now).toISOString(),new Date(now+3600000).toISOString());assert.equal((await runEnrichment(env,{now,registry:registry(),fetcher:success})).status,'leased');const r=await runEnrichment(env,{now:now+2*3600000,registry:registry(),fetcher:success});assert.equal(r.status,'completed');assert.equal(db.sqlite.prepare("SELECT status FROM enrichment_runs WHERE run_id='OLD'").get().status,'failed')});

test('restoring an earlier exact input reactivates work without deleting previous evidence',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);await syncTargets(env,registry({...record,title:'Changed'}),now+1);await syncTargets(env,registry(),now+2);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM enrichment_jobs WHERE status='pending'").get().n,2);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_inputs').get().n,2)});
test('SQL prevents two active runs even when concurrent slots differ',async()=>{const{db}=setup();db.sqlite.exec("INSERT INTO enrichment_runs VALUES ('A','cycle','slot-a','time',NULL,'later','running',NULL,NULL)");assert.throws(()=>db.sqlite.exec("INSERT INTO enrichment_runs VALUES ('B','cycle','slot-b','time',NULL,'later','running',NULL,NULL)"),/UNIQUE/)});
test('three consecutive transient failures exhaust only the affected job',async()=>{const{env,db}=setup();await syncTargets(env,registry(),now);db.sqlite.exec("UPDATE enrichment_jobs SET status='blocked' WHERE kind='citations'");for(const h of [0,1,3])await runEnrichment(env,{now:now+h*3600000,registry:registry(),fetcher:async()=>new Response('',{status:503})});const j=db.sqlite.prepare("SELECT status,failure_streak FROM enrichment_jobs WHERE kind='metadata'").get();assert.equal(j.status,'exhausted');assert.equal(j.failure_streak,3);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_attempts').get().n,3)});
test('deactivating a target prevents new execution but keeps its immutable source',async()=>{const{env,db}=await sourceSetup();await syncTargets(env,{schemaVersion:1,records:[]},now+1);const r=await runEnrichment(env,{now:now+3600000,registry:{schemaVersion:1,records:[]},fetcher:async()=>{throw Error('must not fetch')}});assert.equal(r.status,'empty');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_sources').get().n,1)});
test('source language is validated and generated summaries cannot be source kinds',async()=>{const{env,target}=await sourceSetup();for(const fields of [{language:{}},{evidence_kind:'model_summary'}])await assert.rejects(saveSource(env,target,{provider:'Fixture',source_url:'https://example.org',evidence_kind:'abstract',text:'Test',...fields},now),/invalid_source/)});
test('stale target proposal insertion is atomic',async()=>{const{env,db,target,input}=await sourceSetup();await syncTargets(env,registry({...record,title:'Changed identity input'}),now+1);await assert.rejects(storeExtraction(env,target,input,now+2));assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_proposals').get().n,0);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM enrichment_framework_proposals').get().n,0)});
test('offsets use UTF-16 units rather than Unicode code points',async()=>{const{target,source,input}=await sourceSetup();source.text='\u{1F600}ab';input.spans[0].start_offset=2;input.spans[0].end_offset=4;assert.equal(validateExtraction(input,target,[source]).spans[0].end_offset,4);input.spans[0].end_offset=5;assert.throws(()=>validateExtraction(input,target,[source]),/invalid_source_span/)});
test('payload fields cannot invoke tools or write scientific acceptance',async()=>{const{env,target,input}=await sourceSetup();await assert.rejects(storeExtraction(env,target,{...input,tool_calls:[{name:'publish'}]},now),/schema_extra/)});
