import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../site/paper-sheet-research.js',import.meta.url),'utf8');
class Element{constructor(tag){this.tag=tag;this.children=[];this.value='';this.attributes={}}set textContent(s){this.value=String(s??'');this.children=[]}get textContent(){return this.value+this.children.map(n=>n.textContent).join(' ')}set innerHTML(_){throw Error('HTML injection forbidden')}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=n;this.value=''}setAttribute(k,v){this.attributes[k]=v}}
const record={id:'CAND-SHEET-FIXTURE',title:'Synthetic study',doi:'10.1234/synthetic',sourceLinks:['https://example.org/paper']};
const fact=value=>({status:value===null?'not_reported':'reported',value,origin:'source',evidence_span_ids:value===null?[]:['evidence-1']});
function fixture(summary='Initial context'){
 const r={assessment_state:'unreviewed_proposal',generation_kind:'automated',source_coverage:'abstract_only',updated_at:'2026-09-13T17:00:00Z',protocol_version:'CILE-ENRICH-1',codebook_version:'1.0.0',internal_notes:'not_released',sources:[{id:'source-1',url:'https://example.org/paper',kind:'abstract',version:'Publisher',checked_at:'2026-09-13T17:00:00Z'}],spans:[{id:'evidence-1',source_id:'source-1',locator:'Abstract'}],framework:{status:'proposed',primary:'diagnosis',rationale:{...fact('Describes observed features'),origin:'analyst'},secondary:[{category:'aetiology',rationale:{...fact('Distinct explanatory contribution'),origin:'analyst'}}],alternative:'screening'},studies:[],datasets:[],analyses:[],variable_uses:[],findings:[]};
 for(const k of ['summary','contribution','research_question','infiltration_definition','infiltration_operationalisation','authors_limitations'])r[k]=fact(k==='summary'?summary:null);
 return{schema_version:1,projection_version:'CILE-PUBLIC-RESEARCH-1',candidate:{...record},availability:'available',research:r,revision:'a'.repeat(64)};
}
function setup(fetcher=async()=>{throw Error('offline')}){const c=vm.createContext({document:{createElement:t=>new Element(t)},URL,AbortController,setTimeout,clearTimeout,fetch:fetcher});vm.runInContext(source,c);return c.CILEPaperResearch}
function descendants(n){return[n,...n.children.flatMap(descendants)]}
test('shows primary, secondary, alternative, rationale, source coverage and unvalidated state',()=>{const parent=new Element('section'),api=setup();api.render(parent,fixture());for(const pattern of [/principale proposta: Diagnosi/,/secondaria proposta: Eziologia/,/alternativa registrata: Screening/,/Distinct explanatory contribution/,/Solo abstract/,/non validata scientificamente/,/2026-09-13/,/Non riportato nella fonte consultata/])assert.match(parent.textContent,pattern);assert.ok(descendants(parent).some(n=>n.href==='https://example.org/paper'))});
test('reopening the same paper loads changed analysis without cache or private credentials',async()=>{let summary='Initial context';const calls=[];const api=setup(async(url,options)=>{calls.push({url,cache:options.cache,credentials:options.credentials});return{ok:true,json:async()=>fixture(summary)}});const parent=new Element('section');await api.load(parent,record);assert.match(parent.textContent,/Initial context/);summary='Revised findings';await api.load(parent,record);assert.match(parent.textContent,/Revised findings/);assert.doesNotMatch(parent.textContent,/Initial context/);assert.ok(calls.every(x=>x.cache==='no-store'&&x.credentials==='omit'&&x.url.includes('/api/public-paper-research?')))});
test('network error, stale, absent and withheld research are not conflated',async()=>{const parent=new Element('section'),api=setup();await api.load(parent,record);assert.match(parent.textContent,/non significa che l’analisi sia assente/);for(const state of ['not_assessed','stale','not_registered','withheld']){const data=fixture();data.availability=state;data.research=null;if(state==='not_registered')data.candidate=null;api.render(parent,api.selectRecord(data,record));assert.doesNotMatch(parent.textContent,/principale proposta/);assert.ok(parent.textContent.length>70)}});
test('a delayed response cannot alter another paper sheet',async()=>{let resolve,current=true;const api=setup(()=>new Promise(r=>{resolve=r})),parent=new Element('section');const pending=api.load(parent,record,()=>current);current=false;parent.textContent='Another paper';resolve({ok:true,json:async()=>fixture()});await pending;assert.equal(parent.textContent,'Another paper')});
test('identity/version mismatches and invented confirmation are rejected',()=>{const api=setup();for(const key of ['id','title','doi']){const data=fixture();data.candidate[key]='different';assert.throws(()=>api.selectRecord(data,record))}const data=fixture();data.research.assessment_state='confirmed';assert.throws(()=>api.selectRecord(data,record));data.research.assessment_state='unreviewed_proposal';data.projection_version='old';assert.throws(()=>api.selectRecord(data,record))});
test('literal untrusted strings and unsafe locators remain inert',()=>{const api=setup(),parent=new Element('section'),data=fixture('<img src=x onerror=alert(1)>');data.research.sources[0].url='javascript:alert(1)';api.render(parent,data);assert.match(parent.textContent,/<img/);assert.ok(descendants(parent).every(n=>n.tag!=='img'&&!n.href));assert.equal(api.safeUrl('https://u:p@example.org'),null)});
test('study-specific variables and null results stay linked to their analyses',()=>{const api=setup(),parent=new Element('section'),data=fixture(),r=data.research;r.studies=[{id:'s1',population:fact('First population')},{id:'s2',population:fact('Second population')}];r.analyses=[{id:'a1',study_id:'s1',dataset_ids:[],method:fact('First method')},{id:'a2',study_id:'s2',dataset_ids:[],method:fact('Second method')}];r.variable_uses=[{id:'v1',analysis_id:'a1',dataset_ids:[],original_name:fact('Exposure')}];r.findings=[{id:'f1',analysis_id:'a1',variable_use_ids:['v1'],statement:fact('Null result'),estimate:fact('0'),uncertainty:fact('[-1, 1]')}];api.render(parent,data);const texts=descendants(parent).filter(n=>n.tag==='details').map(n=>n.textContent);assert.ok(texts.some(t=>t.startsWith('Studio 1')&&t.includes('Null result')&&t.includes('Exposure')));assert.ok(texts.some(t=>t.startsWith('Studio 2')&&!t.includes('Null result')))});
test('ordinary and accessible paper openings both load public research separately from support',()=>{const code=fs.readFileSync(new URL('../../site/paper-register.js',import.meta.url),'utf8');assert.match(code,/CILEPaperResearch\.load\(research, record, isCurrent\)/);assert.match(code,/row\.addEventListener\("dblclick"/);assert.doesNotMatch(source,/\/api\/paper-enrichment\//)});
