import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,createHash,createPublicKey,diffieHellman,hkdfSync,createDecipheriv} from 'node:crypto';
import {seal,PROTOCOL} from '../../scripts/enrichment/seal-audit.mjs';
const now=1000000000000;
function setup(){const pair=generateKeyPairSync('x25519'),der=pair.publicKey.export({format:'der',type:'spki'});return{pair,recipient:{protocol:PROTOCOL,public_key_spki:der.toString('base64'),public_key_sha256:createHash('sha256').update(der).digest('hex'),expires_at:new Date(now+10000).toISOString()}}}
function decrypt(e,privateKey){const b=k=>Buffer.from(e[k],'base64');const key=hkdfSync('sha256',diffieHellman({privateKey,publicKey:createPublicKey({key:b('ephemeral_spki'),type:'spki',format:'der'})}),b('salt'),Buffer.from(PROTOCOL),32);const cipher=createDecipheriv('aes-256-gcm',key,b('nonce'));cipher.setAAD(b('aad'));cipher.setAuthTag(b('tag'));return Buffer.concat([cipher.update(b('ciphertext')),cipher.final()]);}
test('audit encryption roundtrips exact bytes but exposes no literal source',()=>{const{pair,recipient}=setup(),p=Buffer.from('Synthetic private evidence, not a real paper.');const e=seal(p,recipient,now);assert.deepEqual(decrypt(e,pair.privateKey),p);assert.ok(!JSON.stringify(e).includes(p.toString()));assert.notEqual(seal(p,recipient,now).ciphertext,e.ciphertext)});
test('wrong recipient or altered audit ciphertext fails authentication',()=>{const{pair,recipient}=setup(),e=seal(Buffer.from('Synthetic'),recipient,now);assert.throws(()=>decrypt(e,generateKeyPairSync('x25519').privateKey));const b=Buffer.from(e.ciphertext,'base64');b[0]^=1;assert.throws(()=>decrypt({...e,ciphertext:b.toString('base64')},pair.privateKey))});
test('expired, modified, wrong-protocol and oversized audit requests fail closed',()=>{const{recipient}=setup();assert.throws(()=>seal(Buffer.from('x'),recipient,now+20000),/expired/);assert.throws(()=>seal(Buffer.from('x'),{...recipient,public_key_sha256:'wrong'},now),/integrity/);assert.throws(()=>seal(Buffer.from('x'),{...recipient,protocol:'other'},now),/invalid/);assert.throws(()=>seal(Buffer.alloc(2000001),recipient,now),/limit/)});
